const TEMP_ACCESS_SECRET_LIVETIME_IN_MS: number = +process.env.TEMP_ACCESS_SECRET_LIVETIME_IN_MS ?? 18000000;
const TEMP_ACCESS_SECRET_LIVETIME_IN_SEC = (TEMP_ACCESS_SECRET_LIVETIME_IN_MS * 0.001) / 60**2;

export { 
    TEMP_ACCESS_SECRET_LIVETIME_IN_MS, 
    TEMP_ACCESS_SECRET_LIVETIME_IN_SEC 
};